### ISSUE TITLE
Links are shown as `http://127.0.0.1:SOME_PORT` instead of the actual link

### ISSUE THREAD

**Issue by tsujp** [diamondburned/6cord#10]
As per the title, pasting any link of any kind results in this behaviour. This is also the case for some inline images including emoticons.

**Comment by diamondburned** [comment]
This is a toggleable feature: https://github.com/diamondburned/6cord/blob/master/6cord.toml#L40

**Comment by tsujp** [comment]
Gotcha, I missed that.

With it enabled it also does it when sending though so recipients see a localhost link too which is probably not intended, no?

**Comment by diamondburned** [comment]
This only work for incoming links, so links that you see. If you want to share the link that you receive, you'll have to open it in a browser and copy that link. 

Sending isn't affected.

**Comment by tsujp** [comment]
Sending was affected for me, I pasted in `google.com` and the receiver saw `127.0.0.1:46338`, this was in a server not a DM.
