### ISSUE TITLE
Character set not supported?

### ISSUE THREAD

**Issue by bsmntoid** [diamondburned/6cord#20]
I'm new to Linux, and upon trying the command `6cord -t "(my discord token)"`It simply says `character set not supported` and kicks me back to the bash terminal. I am on archlinux with KDE Plasma, trying to run this in Konsole. I have no idea whether this is something to do with konsole or with 6cord.

Update: Tried it on xterm, also comes out with the same error

**Comment by diamondburned** [comment]
What are your LANG and LC_ALL variables set to?

**Comment by bsmntoid** [comment]
LANG is set to en.US.UTF-8
LC_ALL is set to nothing.

**Comment by diamondburned** [comment]
Try with `LANG=en_US.UTF-8`.

**Comment by bsmntoid** [comment]
That seems to have fixed it. Thank you!
