### ISSUE TITLE
Unable to open with token or user/password

### ISSUE THREAD

**Issue by jgc37** [diamondburned/6cord#4]
Whenever I try to use a token or the username and password I get 
`exit status 1`
Whenever I try to run it normally I get
`panic: failed to unlock correct collection /org/freedesktop/secrets/aliases/default`

**Comment by diamondburned** [comment]
Check `/tmp/6cord.log`

**Comment by jgc37** [comment]
`2019/06/20 12:11:59 main.go:424: Failed to set keyring! Continuing anyway... failed to unlock correct collection '/org/freedesktop/secrets/aliases/default'
2019/06/20 12:11:59 main.go:351: Discordgo: 2 2 [S0:CID1]: closing gateway connection []
2019/06/20 12:11:59 main.go:355: ([]interface {}) <nil>

2019/06/20 12:12:00 main.go:351: Discordgo: 0 2 [S0:CID1]: got close frame, code: %d, Msg: %q [1002 ]
2019/06/20 12:12:00 main.go:355: ([]interface {}) (len=2 cap=2) {
 (uint16) 1002,
 (string) ""
}

2019/06/20 12:12:00 main.go:385: (*discordgo.Disconnect)(0x15b8458)({
})

panic: exit status 1

goroutine 1 [running]:
main.main()
`

**Comment by diamondburned** [comment]
What terminal is this?

**Comment by jgc37** [comment]
>What terminal is this?

@diamondburned Urxvt

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by diamondburned** [comment]
Known issue: https://gitlab.com/diamondburned/6cord/issues/21

Track it there instead.
