### ISSUE TITLE
infocmp failed: exit status 1

### ISSUE THREAD

**Issue by TotNotTac** [diamondburned/6cord#8]
`infocmp failed: exit status 1`
I get the error if I try to launch `6cord -t <token>` (linux).
I'm not sure if there's any log files and where I would find them, if I do find it, I'll include them.

**Comment by TotNotTac** [comment]
Used another terminal and it works now

**Comment by sverona** [comment]
Confirming that this issue is solved by switching to xterm. Alacritty also works. xst does not.

**Comment by diamondburned** [comment]
xst may use its custom `$TERM`, an override should work: `TERM=xterm-256color 6cord`.
